### ISSUE TITLE
topRelated calls exceeded the Quota

### ISSUE THREAD

**Issue by DWboutin** [pat310/google-trends-api#42]
How it have a Quota if i don't enter an api key?

[ Error: Quota limit exceeded, try again later
at parseHtml (/Users/name/Desktop/apiproject/node_modules/google-trends-api/lib/resources/htmlParser.js:5:46)
at /Users/name/Desktop/apiproject/node_modules/google-trends-api/lib/utils/topRelated.js:25:11
at tryCatcher (/Users/name/Desktop/apiproject/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/Users/name/Desktop/apiproject/node_modules/bluebird/js/release/promise.js:510:31)
at Promise._settlePromise (/Users/name/Desktop/apiproject/node_modules/bluebird/js/release/promise.js:567:18)
at Promise._settlePromise0 (/Users/name/Desktop/apiproject/node_modules/bluebird/js/release/promise.js:612:10)
at Promise._settlePromises (/Users/name/Desktop/apiproject/node_modules/bluebird/js/release/promise.js:691:18)
at Async._drainQueue (/Users/name/Desktop/apiproject/node_modules/bluebird/js/release/async.js:138:16)
at Async._drainQueues (/Users/name/Desktop/apiproject/node_modules/bluebird/js/release/async.js:148:10)
at Immediate.Async.drainQueues (/Users/name/Desktop/apiproject/node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:574:20)
at tryOnImmediate (timers.js:554:5)
at processImmediate [as _immediateCallback] (timers.js:533:5),
Error: Quota limit exceeded, try again later
at parseHtml (/Users/name/Desktop/apiproject/node_modules/google-trends-api/lib/resources/htmlParser.js:5:46)
at /Users/name/Desktop/apiproject/node_modules/google-trends-api/lib/utils/topRelated.js:25:11
at tryCatcher (/Users/name/Desktop/apiproject/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/Users/name/Desktop/apiproject/node_modules/bluebird/js/release/promise.js:510:31)
at Promise._settlePromise (/Users/name/Desktop/apiproject/node_modules/bluebird/js/release/promise.js:567:18)
at Promise._settlePromise0 (/Users/name/Desktop/apiproject/node_modules/bluebird/js/release/promise.js:612:10)
at Promise._settlePromises (/Users/name/Desktop/apiproject/node_modules/bluebird/js/release/promise.js:691:18)
at Async._drainQueue (/Users/name/Desktop/apiproject/node_modules/bluebird/js/release/async.js:138:16)
at Async._drainQueues (/Users/name/Desktop/apiproject/node_modules/bluebird/js/release/async.js:148:10)
at Immediate.Async.drainQueues (/Users/name/Desktop/apiproject/node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:574:20)
at tryOnImmediate (timers.js:554:5)
at processImmediate [as _immediateCallback] (timers.js:533:5) ]

**Comment by Dayjo** [comment]
Hi @DWboutin,

Please see this issue here; https://github.com/pat310/google-trends-api/issues/36

**Comment by pat310** [comment]
@DWboutin Should be corrected now hopefully with #47.  Grabbing a token and attaching it as a query parameter.
